### ISSUE TITLE
DNS-Swapper failed after saving config which probably is wrong. How to cleanup configuration in such case?

### ISSUE THREAD

**Issue by fwalk** [tryallthethings/DNS-Swapper#3]
Hi 
today i played arouond with pi-hole and liked to switch the nameserver with DNS-Swapper. 
Installation works perfect. 

After saving a config and trying to restart DNS-Swapper it was short visible in the taskbar but disappears after the mouse was moved over the icon.

Re-install did not help. 
How can i cleanup a probably wrong saved configuration.

Faulting application name: DNS-Swapper.exe, version: 1.0.0.0, time stamp: 0x5a53c013
Faulting module name: KERNELBASE.dll, version: 10.0.17134.137, time stamp: 0x16722c9d
Exception code: 0xe0434352
Fault offset: 0x0010db92
Faulting process id: 0xf28
Faulting application start time: 0x01d416b81a0de0d5
Faulting application path: C:\Program Files\DNS-Swapper\DNS-Swapper.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 987ff205-ef9b-4995-85ce-9b615def94f7
Faulting package full name: 
Faulting package-relative application ID: 

Thx for your work on this project.

**Comment by tryallthethings** [comment]
Hello! 
The configuration is currently saved in %LOCALAPPDATA%\DNS_Swapper - so for example C:\Users\username\AppData\Local\DNS_Swapper\DNS-Swapper.exe_Url_2vkzryni5blagkgybxtiai1dd3qne5zd\1.0.0.0\user.config. Just close DNS-Swapper, remove the folder / all folders and start it up again:
![image](https://user-images.githubusercontent.com/11146296/42632913-1c81c3c2-85df-11e8-8e41-bf8cc8bbe876.png)
You'll have to configure DNS-Swapper again.

Let me know if that solves your problem.

**Comment by tryallthethings** [comment]
Could you probably post the configuration before deleting so I see what went wrong?

**Comment by tomac01** [comment]
I have the same or a similar problem:
As soon as I save network interface to the configuration, DNS swapper can not be opened anymore; he  crashes to desktop.

Here is the content of the config file:
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <userSettings>
        <DNS_Swapper.Properties.Settings>
            <setting name="NIC" serializeAs="String">
                <value>Intel(R) Ethernet Connection (2) I219-V</value>
            </setting>
            <setting name="DNS_1" serializeAs="String">
                <value>1  .1  .1  .1</value>
            </setting>
            <setting name="DNS_2" serializeAs="String">
                <value>192.168.10 .10</value>
            </setting>
        </DNS_Swapper.Properties.Settings>
    </userSettings>
</configuration>`

**Comment by tryallthethings** [comment]
I can't say if this is the same issue since OP never responded but the configuration file you provided certainly helped. There is a problem with how I save the DNS-Servers into the configuration file and single / double digit numbers in the first 3 positions of the IP-Address. I will look into it and release a new version

**Comment by tryallthethings** [comment]
New version released which should solve the mentioned issues: https://github.com/roots84/DNS-Swapper/releases/tag/b%2F1.3
